# Configuracion compartida para todos los microservicios
spring:
  # OAuth2 Resource Server (valida tokens de Keycloak)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:9000/realms/banco-xyz
          jwk-set-uri: http://host.docker.internal:9000/realms/banco-xyz/protocol/openid-connect/certs

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.bancoxyz: DEBUG
